#!/bin/bash

if [[ $(iwgetid -r) == "" ]]; then
	echo "WifiDown" 
else
	echo \"$(iwgetid -r | cut -c 1-4)..\"  $(iwconfig | grep -o -P "(?<=Bit Rate:)[0-9]* .b/s") 
fi

case $BLOCK_BUTTON in
    1) 
        #i3-sensible-terminal &
        ;;
    2)
        #$pulsectl mi
        ;;
    3)
        ;;
esac
