#!/bin/bash

wins=`xdotool search --all --onlyvisible --desktop $(xprop -notype -root _NET_CURRENT_DESKTOP | cut -c 24-) "" 2>/dev/null`
args=""
tmpbg=/tmp/screen.png

for win in $wins 
do
	dim=`xwininfo -id $win |
    	sed -n -e "s/^ \+Absolute upper-left X: \+\([0-9]\+\).*/\1/p" \
           -e "s/^ \+Absolute upper-left Y: \+\([0-9]\+\).*/\1/p" \
           -e "s/^ \+Width: \+\([0-9]\+\).*/\1/p" \
	   -e "s/^ \+Height: \+\([0-9]\+\).*/\1/p"`
	if [ $win == `xdotool getactivewindow` ] 
	then
		class=`xprop -id $win | sed -n -e "s/^WM_CLASS(STRING) = \".*\", \"\(.*\)\"/\1/p"`
		if [  $class == "Xfce4-terminal" ]
		then
			dim="$dim 230"
		else
			dim="$dim 256"
		fi
	else
		dim="$dim 154"		
	fi	
	args="$args $dim"
done
wallpaper=`bgctl info | sed -n -e "s/^Current Wallpaper: \+\(.*\)/\1/p"`
killall -r "compton"
scrot "$tmpbg"
python3 ~/.config/i3/scripts/makepic.py $wallpaper $args
icon=`ls $HOME/Pictures/locks/*.png | shuf -n 1`
convert "$tmpbg" "$icon" -gravity center -composite -matte "$tmpbg"
i3lock -u -i "$tmpbg"
compton --config ~/.config/compton/compton.conf -b

